<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Auctioning Used-Car Classifier</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Auctioning Used-Car Classifier</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="author-andrew-tran" class="level4">
<h4 class="anchored" data-anchor-id="author-andrew-tran">Author: Andrew Tran</h4>
</section>
<section id="blog-post-inspiration-and-objectives" class="level2">
<h2 class="anchored" data-anchor-id="blog-post-inspiration-and-objectives">Blog Post Inspiration and Objectives</h2>
<p>In this blog post, I was hoping to take on answering the applying my basic understanding of classification that was taught in this Machine Learning course early in the semseter. Additionally, I was interested in the traditional questions posed by those in the college and just graduating from it as most try to purchase their first car. Specifically, what factors lead to a mutually beneficial first starter car. In the general sense, this dataset does not have a strong corrleation to be applied with Machine Learning algorithms, but I thought I gave it a chance. Through seeing the profit made by selling the car compared to its market-valued price, determining the return-of-investment (ROI) made on the vehicle introduces the concept of binary classification here. With that being said, let’s try to tackle this problem with some Machine Learning:</p>
</section>
<section id="data-preprocessing---cleaning-and-analytics" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing---cleaning-and-analytics">Data Preprocessing - Cleaning and Analytics</h2>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import needed libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> datetime <span class="im">as</span> dt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sklearn <span class="im">as</span> sk</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> MinMaxScaler, StandardScaler</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, roc_auc_score, confusion_matrix, classification_report, precision_recall_fscore_support</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> KNeighborsClassifier</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">"fivethirtyeight"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First, we will read and display the initial dataset in our file system for this blog post, downloaded from Kaggle. This dataset contains loads of valuable information such as every car’s specifications (trim, type of transmission, make, model, color, interior, etc.), state sold, selling price, etc.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading and displaying the initial dataset (ignoring any warnings or errors)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"datasets/car_prices.csv"</span>, error_bad_lines<span class="op">=</span><span class="va">False</span>, warn_bad_lines<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\andre\AppData\Local\Temp\ipykernel_13416\331717344.py:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv("datasets/car_prices.csv", error_bad_lines=False, warn_bad_lines=False)
C:\Users\andre\AppData\Local\Temp\ipykernel_13416\331717344.py:2: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv("datasets/car_prices.csv", error_bad_lines=False, warn_bad_lines=False)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">make</th>
<th data-quarto-table-cell-role="th">model</th>
<th data-quarto-table-cell-role="th">trim</th>
<th data-quarto-table-cell-role="th">body</th>
<th data-quarto-table-cell-role="th">transmission</th>
<th data-quarto-table-cell-role="th">vin</th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">condition</th>
<th data-quarto-table-cell-role="th">odometer</th>
<th data-quarto-table-cell-role="th">color</th>
<th data-quarto-table-cell-role="th">interior</th>
<th data-quarto-table-cell-role="th">seller</th>
<th data-quarto-table-cell-role="th">mmr</th>
<th data-quarto-table-cell-role="th">sellingprice</th>
<th data-quarto-table-cell-role="th">saledate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg566472</td>
<td>ca</td>
<td>5.0</td>
<td>16639.0</td>
<td>white</td>
<td>black</td>
<td>kia motors america, inc</td>
<td>20500</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg561319</td>
<td>ca</td>
<td>5.0</td>
<td>9393.0</td>
<td>white</td>
<td>beige</td>
<td>kia motors america, inc</td>
<td>20800</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2014</td>
<td>BMW</td>
<td>3 Series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba3c1c51ek116351</td>
<td>ca</td>
<td>4.5</td>
<td>1331.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>31900</td>
<td>30000</td>
<td>Thu Jan 15 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>automatic</td>
<td>yv1612tb4f1310987</td>
<td>ca</td>
<td>4.1</td>
<td>14282.0</td>
<td>white</td>
<td>black</td>
<td>volvo na rep/world omni</td>
<td>27500</td>
<td>27750</td>
<td>Thu Jan 29 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2014</td>
<td>BMW</td>
<td>6 Series Gran Coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba6b2c57ed129731</td>
<td>ca</td>
<td>4.3</td>
<td>2641.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>66000</td>
<td>67000</td>
<td>Thu Dec 18 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558806</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>NaN</td>
<td>knalw4d4xf6019304</td>
<td>in</td>
<td>4.5</td>
<td>18255.0</td>
<td>silver</td>
<td>black</td>
<td>avis corporation</td>
<td>35300</td>
<td>33000</td>
<td>Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558807</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crew Cab</td>
<td>automatic</td>
<td>3c6td5et6cg112407</td>
<td>wa</td>
<td>5.0</td>
<td>54393.0</td>
<td>white</td>
<td>black</td>
<td>i -5 uhlmann rv</td>
<td>30200</td>
<td>30800</td>
<td>Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558808</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>SUV</td>
<td>automatic</td>
<td>5uxzw0c58cl668465</td>
<td>ca</td>
<td>4.8</td>
<td>50561.0</td>
<td>black</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>29800</td>
<td>34000</td>
<td>Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558809</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>sedan</td>
<td>automatic</td>
<td>1n4al3ap0fc216050</td>
<td>ga</td>
<td>3.8</td>
<td>16658.0</td>
<td>white</td>
<td>black</td>
<td>enterprise vehicle exchange / tra / rental / t...</td>
<td>15100</td>
<td>11100</td>
<td>Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558810</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>SuperCrew</td>
<td>automatic</td>
<td>1ftfw1et2eke87277</td>
<td>ca</td>
<td>3.4</td>
<td>15008.0</td>
<td>gray</td>
<td>gray</td>
<td>ford motor credit company,llc pd</td>
<td>29600</td>
<td>26700</td>
<td>Thu May 28 2015 05:30:00 GMT-0700 (PDT)</td>
</tr>
</tbody>
</table>

<p>558811 rows × 16 columns</p>
</div>
</div>
</div>
<p>For clarity on the constraints and parameters of the working datasets, I went to find high-level exploratory statistics on all of the datasets: shape, information about all of the entries, etc.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determining the shape of the initial dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>(558811, 16)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting a sample of the initial dataset through the seeing the first 10 entries</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># completely in the dataset</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">make</th>
<th data-quarto-table-cell-role="th">model</th>
<th data-quarto-table-cell-role="th">trim</th>
<th data-quarto-table-cell-role="th">body</th>
<th data-quarto-table-cell-role="th">transmission</th>
<th data-quarto-table-cell-role="th">vin</th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">condition</th>
<th data-quarto-table-cell-role="th">odometer</th>
<th data-quarto-table-cell-role="th">color</th>
<th data-quarto-table-cell-role="th">interior</th>
<th data-quarto-table-cell-role="th">seller</th>
<th data-quarto-table-cell-role="th">mmr</th>
<th data-quarto-table-cell-role="th">sellingprice</th>
<th data-quarto-table-cell-role="th">saledate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg566472</td>
<td>ca</td>
<td>5.0</td>
<td>16639.0</td>
<td>white</td>
<td>black</td>
<td>kia motors america, inc</td>
<td>20500</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg561319</td>
<td>ca</td>
<td>5.0</td>
<td>9393.0</td>
<td>white</td>
<td>beige</td>
<td>kia motors america, inc</td>
<td>20800</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2014</td>
<td>BMW</td>
<td>3 Series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba3c1c51ek116351</td>
<td>ca</td>
<td>4.5</td>
<td>1331.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>31900</td>
<td>30000</td>
<td>Thu Jan 15 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>automatic</td>
<td>yv1612tb4f1310987</td>
<td>ca</td>
<td>4.1</td>
<td>14282.0</td>
<td>white</td>
<td>black</td>
<td>volvo na rep/world omni</td>
<td>27500</td>
<td>27750</td>
<td>Thu Jan 29 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2014</td>
<td>BMW</td>
<td>6 Series Gran Coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba6b2c57ed129731</td>
<td>ca</td>
<td>4.3</td>
<td>2641.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>66000</td>
<td>67000</td>
<td>Thu Dec 18 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Figuring out all of the columns (and their names) available for me to use in </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the dataset</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')</code></pre>
</div>
</div>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting basic information about the dataset</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 558811 entries, 0 to 558810
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   year          558811 non-null  int64  
 1   make          548510 non-null  object 
 2   model         548412 non-null  object 
 3   trim          548160 non-null  object 
 4   body          545616 non-null  object 
 5   transmission  493458 non-null  object 
 6   vin           558811 non-null  object 
 7   state         558811 non-null  object 
 8   condition     547017 non-null  float64
 9   odometer      558717 non-null  float64
 10  color         558062 non-null  object 
 11  interior      558062 non-null  object 
 12  seller        558811 non-null  object 
 13  mmr           558811 non-null  int64  
 14  sellingprice  558811 non-null  int64  
 15  saledate      558811 non-null  object 
dtypes: float64(2), int64(3), object(11)
memory usage: 68.2+ MB</code></pre>
</div>
</div>
<p>Additionally, before handing my combined Book dataset over for Machine Learning training and prediction, I need to clean the data prior to the analysis stage: removing duplicates, deleting null/NaN vales, fixing types of columns, filling invalid values with suitable alternatives, etc.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Figuring out the number of duplicated elements in the dataset (could be </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># problematic if not resolved)</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>df.duplicated().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0</code></pre>
</div>
</div>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Renaming the columns to be more readable </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">"sellingprice"</span>: <span class="st">"Selling Price"</span>, <span class="st">"saledate"</span>: <span class="st">"Sale Date"</span>})</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>cols_rename_dict <span class="op">=</span> {}</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df.columns:</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    cols_rename_dict.update({col: <span class="bu">str</span>(col[<span class="dv">0</span>].upper() <span class="op">+</span> col[<span class="dv">1</span>:])})</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>cols_rename_dict)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">Mmr</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg566472</td>
<td>ca</td>
<td>5.0</td>
<td>16639.0</td>
<td>white</td>
<td>black</td>
<td>kia motors america, inc</td>
<td>20500</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg561319</td>
<td>ca</td>
<td>5.0</td>
<td>9393.0</td>
<td>white</td>
<td>beige</td>
<td>kia motors america, inc</td>
<td>20800</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2014</td>
<td>BMW</td>
<td>3 Series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba3c1c51ek116351</td>
<td>ca</td>
<td>4.5</td>
<td>1331.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>31900</td>
<td>30000</td>
<td>Thu Jan 15 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>automatic</td>
<td>yv1612tb4f1310987</td>
<td>ca</td>
<td>4.1</td>
<td>14282.0</td>
<td>white</td>
<td>black</td>
<td>volvo na rep/world omni</td>
<td>27500</td>
<td>27750</td>
<td>Thu Jan 29 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2014</td>
<td>BMW</td>
<td>6 Series Gran Coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba6b2c57ed129731</td>
<td>ca</td>
<td>4.3</td>
<td>2641.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>66000</td>
<td>67000</td>
<td>Thu Dec 18 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558806</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>NaN</td>
<td>knalw4d4xf6019304</td>
<td>in</td>
<td>4.5</td>
<td>18255.0</td>
<td>silver</td>
<td>black</td>
<td>avis corporation</td>
<td>35300</td>
<td>33000</td>
<td>Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558807</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crew Cab</td>
<td>automatic</td>
<td>3c6td5et6cg112407</td>
<td>wa</td>
<td>5.0</td>
<td>54393.0</td>
<td>white</td>
<td>black</td>
<td>i -5 uhlmann rv</td>
<td>30200</td>
<td>30800</td>
<td>Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558808</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>SUV</td>
<td>automatic</td>
<td>5uxzw0c58cl668465</td>
<td>ca</td>
<td>4.8</td>
<td>50561.0</td>
<td>black</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>29800</td>
<td>34000</td>
<td>Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558809</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>sedan</td>
<td>automatic</td>
<td>1n4al3ap0fc216050</td>
<td>ga</td>
<td>3.8</td>
<td>16658.0</td>
<td>white</td>
<td>black</td>
<td>enterprise vehicle exchange / tra / rental / t...</td>
<td>15100</td>
<td>11100</td>
<td>Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558810</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>SuperCrew</td>
<td>automatic</td>
<td>1ftfw1et2eke87277</td>
<td>ca</td>
<td>3.4</td>
<td>15008.0</td>
<td>gray</td>
<td>gray</td>
<td>ford motor credit company,llc pd</td>
<td>29600</td>
<td>26700</td>
<td>Thu May 28 2015 05:30:00 GMT-0700 (PDT)</td>
</tr>
</tbody>
</table>

<p>558811 rows × 16 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Figuring out the number of 'null'/'NaN' elements in the dataset (i.e. if NaN </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># filling is needed or not)</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.isnull().<span class="bu">sum</span>())</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>(df.isnull().<span class="bu">sum</span>() <span class="op">/</span> df.shape[<span class="dv">0</span>]) <span class="op">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Year                 0
Make             10301
Model            10399
Trim             10651
Body             13195
Transmission     65353
Vin                  0
State                0
Condition        11794
Odometer            94
Color              749
Interior           749
Seller               0
Mmr                  0
Selling Price        0
Sale Date            0
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>Year              0.000000
Make              1.843378
Model             1.860915
Trim              1.906011
Body              2.361263
Transmission     11.695010
Vin               0.000000
State             0.000000
Condition         2.110553
Odometer          0.016821
Color             0.134035
Interior          0.134035
Seller            0.000000
Mmr               0.000000
Selling Price     0.000000
Sale Date         0.000000
dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill unknown and unformatted values with proper ones for readability and to</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># improve data accuracy and relevance </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Make"</span>].fillna(<span class="st">"(Unknown)"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Make"</span>].replace(<span class="st">"Mercedes-Benz"</span>, <span class="st">"M-Benz"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Make"</span>].replace(<span class="st">"Volkswagen"</span>, <span class="st">"VW"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Model"</span>].fillna(<span class="st">"(Unknown)"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Trim"</span>].fillna(<span class="st">"(Unknown)"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">"Body"</span>].unique(), <span class="bu">len</span>(df[<span class="st">"Body"</span>].unique()))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>].fillna(df[<span class="st">"Body"</span>].mode()[<span class="dv">0</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>].replace(<span class="st">"G Sedan"</span>, <span class="st">"gsedan"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>].replace(<span class="st">"g sedan"</span>, <span class="st">"gsedan"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>].replace(<span class="st">"Crew Cab"</span>, <span class="st">"Crewcab"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>].replace(<span class="st">"crew cab"</span>, <span class="st">"crewcab"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Transmission"</span>].fillna(<span class="st">"Manual"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Odometer"</span>].fillna(df[<span class="st">"Odometer"</span>].mean(), inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Condition"</span>].fillna(df[<span class="st">"Condition"</span>].mode()[<span class="dv">0</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Color"</span>].fillna(<span class="st">"(Unknown)"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Color"</span>].replace(<span class="st">"—"</span>, <span class="st">"(Unknown)"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Interior"</span>].fillna(df[<span class="st">"Interior"</span>].mode()[<span class="dv">0</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['SUV' 'Sedan' 'Convertible' 'Coupe' 'Wagon' 'Hatchback' 'Crew Cab'
 'G Coupe' 'G Sedan' 'Elantra Coupe' 'Genesis Coupe' 'Minivan' nan 'Van'
 'Double Cab' 'CrewMax Cab' 'Access Cab' 'King Cab' 'SuperCrew'
 'CTS Coupe' 'Extended Cab' 'E-Series Van' 'SuperCab' 'Regular Cab'
 'G Convertible' 'Koup' 'Quad Cab' 'CTS-V Coupe' 'sedan' 'G37 Convertible'
 'Club Cab' 'Xtracab' 'Q60 Convertible' 'CTS Wagon' 'convertible'
 'G37 Coupe' 'Mega Cab' 'Cab Plus 4' 'Q60 Coupe' 'Cab Plus'
 'Beetle Convertible' 'TSX Sport Wagon' 'Promaster Cargo Van'
 'GranTurismo Convertible' 'CTS-V Wagon' 'Ram Van' 'minivan' 'suv'
 'Transit Van' 'van' 'regular-cab' 'g sedan' 'g coupe' 'hatchback'
 'king cab' 'supercrew' 'g convertible' 'coupe' 'crew cab' 'wagon'
 'double cab' 'e-series van' 'regular cab' 'quad cab' 'g37 convertible'
 'supercab' 'extended cab' 'crewmax cab' 'genesis coupe' 'access cab'
 'mega cab' 'xtracab' 'beetle convertible' 'cts coupe' 'koup' 'club cab'
 'elantra coupe' 'q60 coupe' 'cts-v coupe' 'transit van'
 'granturismo convertible' 'tsx sport wagon' 'promaster cargo van'
 'q60 convertible' 'g37 coupe' 'cab plus 4' 'cts wagon'] 87</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">Mmr</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg566472</td>
<td>ca</td>
<td>5.0</td>
<td>16639.0</td>
<td>white</td>
<td>black</td>
<td>kia motors america, inc</td>
<td>20500</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>SUV</td>
<td>automatic</td>
<td>5xyktca69fg561319</td>
<td>ca</td>
<td>5.0</td>
<td>9393.0</td>
<td>white</td>
<td>beige</td>
<td>kia motors america, inc</td>
<td>20800</td>
<td>21500</td>
<td>Tue Dec 16 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2014</td>
<td>BMW</td>
<td>3 Series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba3c1c51ek116351</td>
<td>ca</td>
<td>4.5</td>
<td>1331.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>31900</td>
<td>30000</td>
<td>Thu Jan 15 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>automatic</td>
<td>yv1612tb4f1310987</td>
<td>ca</td>
<td>4.1</td>
<td>14282.0</td>
<td>white</td>
<td>black</td>
<td>volvo na rep/world omni</td>
<td>27500</td>
<td>27750</td>
<td>Thu Jan 29 2015 04:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2014</td>
<td>BMW</td>
<td>6 Series Gran Coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>automatic</td>
<td>wba6b2c57ed129731</td>
<td>ca</td>
<td>4.3</td>
<td>2641.0</td>
<td>gray</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>66000</td>
<td>67000</td>
<td>Thu Dec 18 2014 12:30:00 GMT-0800 (PST)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558806</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>knalw4d4xf6019304</td>
<td>in</td>
<td>4.5</td>
<td>18255.0</td>
<td>silver</td>
<td>black</td>
<td>avis corporation</td>
<td>35300</td>
<td>33000</td>
<td>Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558807</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crewcab</td>
<td>automatic</td>
<td>3c6td5et6cg112407</td>
<td>wa</td>
<td>5.0</td>
<td>54393.0</td>
<td>white</td>
<td>black</td>
<td>i -5 uhlmann rv</td>
<td>30200</td>
<td>30800</td>
<td>Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558808</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>SUV</td>
<td>automatic</td>
<td>5uxzw0c58cl668465</td>
<td>ca</td>
<td>4.8</td>
<td>50561.0</td>
<td>black</td>
<td>black</td>
<td>financial services remarketing (lease)</td>
<td>29800</td>
<td>34000</td>
<td>Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558809</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>sedan</td>
<td>automatic</td>
<td>1n4al3ap0fc216050</td>
<td>ga</td>
<td>3.8</td>
<td>16658.0</td>
<td>white</td>
<td>black</td>
<td>enterprise vehicle exchange / tra / rental / t...</td>
<td>15100</td>
<td>11100</td>
<td>Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558810</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>SuperCrew</td>
<td>automatic</td>
<td>1ftfw1et2eke87277</td>
<td>ca</td>
<td>3.4</td>
<td>15008.0</td>
<td>gray</td>
<td>gray</td>
<td>ford motor credit company,llc pd</td>
<td>29600</td>
<td>26700</td>
<td>Thu May 28 2015 05:30:00 GMT-0700 (PDT)</td>
</tr>
</tbody>
</table>

<p>558811 rows × 16 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check to make sure if all NaN and also any unpreferred / unformatted values</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># are resolved now</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.isnull().<span class="bu">sum</span>())</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>(df.isnull().<span class="bu">sum</span>() <span class="op">/</span> df.shape[<span class="dv">0</span>]) <span class="op">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Year             0
Make             0
Model            0
Trim             0
Body             0
Transmission     0
Vin              0
State            0
Condition        0
Odometer         0
Color            0
Interior         0
Seller           0
Mmr              0
Selling Price    0
Sale Date        0
dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>Year             0.0
Make             0.0
Model            0.0
Trim             0.0
Body             0.0
Transmission     0.0
Vin              0.0
State            0.0
Condition        0.0
Odometer         0.0
Color            0.0
Interior         0.0
Seller           0.0
Mmr              0.0
Selling Price    0.0
Sale Date        0.0
dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert columns with quantitative data to have a numerical representation </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Year"</span>] <span class="op">=</span> df[<span class="st">"Year"</span>].<span class="bu">apply</span>(<span class="bu">int</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"State"</span>] <span class="op">=</span> df[<span class="st">"State"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: x.upper())</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix the capitalization on the entries in the columns for readability</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> capitalize_first_letter(entry: <span class="bu">str</span>):</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> entry <span class="op">==</span> <span class="st">"M-Benz"</span> <span class="kw">or</span> entry <span class="op">==</span> <span class="st">"VW"</span> <span class="kw">or</span> entry <span class="op">==</span> <span class="st">"BMW"</span>:</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> entry</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> entry[<span class="dv">0</span>] <span class="op">==</span> <span class="st">"("</span>:</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> entry[:<span class="dv">2</span>].upper() <span class="op">+</span> entry[<span class="dv">2</span>:].lower()</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> entry[<span class="dv">0</span>].upper() <span class="op">+</span> entry[<span class="dv">1</span>:].lower()</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Make"</span>] <span class="op">=</span> df[<span class="st">"Make"</span>].<span class="bu">apply</span>(capitalize_first_letter)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Model"</span>] <span class="op">=</span> df[<span class="st">"Model"</span>].<span class="bu">apply</span>(capitalize_first_letter)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>] <span class="op">=</span> df[<span class="st">"Body"</span>].<span class="bu">apply</span>(capitalize_first_letter)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Transmission"</span>] <span class="op">=</span> df[<span class="st">"Transmission"</span>].<span class="bu">apply</span>(capitalize_first_letter)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Color"</span>] <span class="op">=</span> df[<span class="st">"Color"</span>].<span class="bu">apply</span>(capitalize_first_letter)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Interior"</span>] <span class="op">=</span> df[<span class="st">"Interior"</span>].<span class="bu">apply</span>(capitalize_first_letter)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> capitalize_first_letter_for_phrase(phrase: <span class="bu">str</span>):</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>    phrase_list: <span class="bu">list</span> <span class="op">=</span> phrase.split()</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    phrase_list <span class="op">=</span> [capitalize_first_letter(entry) <span class="cf">for</span> entry <span class="kw">in</span> phrase_list]</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">" "</span>.join(phrase_list)</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Seller"</span>] <span class="op">=</span> [capitalize_first_letter_for_phrase(entry) <span class="cf">for</span> entry <span class="kw">in</span> df[<span class="st">"Seller"</span>]]</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the "Sales Date" column to become a parsable datetime object</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> str_to_datetime(date_str: <span class="bu">str</span>):</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>    month_dict <span class="op">=</span> {<span class="st">"Jan"</span>: <span class="dv">1</span>, <span class="st">"Feb"</span>: <span class="dv">2</span>, <span class="st">"Mar"</span>: <span class="dv">3</span>, <span class="st">"Apr"</span>: <span class="dv">4</span>, <span class="st">"May"</span>: <span class="dv">5</span>, <span class="st">"Jun"</span>: <span class="dv">6</span>, </span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Jul"</span>: <span class="dv">7</span>, <span class="st">"Aug"</span>: <span class="dv">8</span>, <span class="st">"Sep"</span>: <span class="dv">9</span>, <span class="st">"Oct"</span>: <span class="dv">10</span>, <span class="st">"Nov"</span>: <span class="dv">11</span>, <span class="st">"Dec"</span>: <span class="dv">12</span>}</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>    time_str_split <span class="op">=</span> <span class="bu">tuple</span>(<span class="bu">str</span>(date_str).split())</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>    month, day, year <span class="op">=</span> month_dict[time_str_split[<span class="dv">1</span>]], <span class="bu">int</span>(time_str_split[<span class="dv">2</span>]), <span class="bu">int</span>(time_str_split[<span class="dv">3</span>])</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>    smaller_time_str_split <span class="op">=</span> <span class="bu">tuple</span>(<span class="bu">str</span>(time_str_split[<span class="dv">4</span>]).split(<span class="st">":"</span>))</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>    hours, minutes, seconds <span class="op">=</span> <span class="bu">int</span>(smaller_time_str_split[<span class="dv">0</span>]), <span class="bu">int</span>(smaller_time_str_split[<span class="dv">1</span>]), <span class="bu">int</span>(smaller_time_str_split[<span class="dv">2</span>])    </span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dt.datetime(year, month, day, hours, minutes, seconds)</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Sale Date"</span>] <span class="op">=</span> df[<span class="st">"Sale Date"</span>].<span class="bu">apply</span>(str_to_datetime)</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">Mmr</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>5xyktca69fg566472</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>5xyktca69fg561319</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>wba3c1c51ek116351</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>Automatic</td>
<td>yv1612tb4f1310987</td>
<td>CA</td>
<td>4.1</td>
<td>14282.0</td>
<td>White</td>
<td>Black</td>
<td>Volvo Na Rep/world Omni</td>
<td>27500</td>
<td>27750</td>
<td>2015-01-29 04:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>wba6b2c57ed129731</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558806</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>knalw4d4xf6019304</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558807</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>3c6td5et6cg112407</td>
<td>WA</td>
<td>5.0</td>
<td>54393.0</td>
<td>White</td>
<td>Black</td>
<td>I -5 Uhlmann Rv</td>
<td>30200</td>
<td>30800</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558808</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>5uxzw0c58cl668465</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">558809</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>1n4al3ap0fc216050</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">558810</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>1ftfw1et2eke87277</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
</tr>
</tbody>
</table>

<p>558811 rows × 16 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Making the "Vin" column the new index (better identifer/key in dataset)</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df.index <span class="op">=</span> df.pop(<span class="st">"Vin"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">Mmr</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5xyktca69fg566472</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5xyktca69fg561319</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba3c1c51ek116351</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">yv1612tb4f1310987</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.1</td>
<td>14282.0</td>
<td>White</td>
<td>Black</td>
<td>Volvo Na Rep/world Omni</td>
<td>27500</td>
<td>27750</td>
<td>2015-01-29 04:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba6b2c57ed129731</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">knalw4d4xf6019304</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3c6td5et6cg112407</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>WA</td>
<td>5.0</td>
<td>54393.0</td>
<td>White</td>
<td>Black</td>
<td>I -5 Uhlmann Rv</td>
<td>30200</td>
<td>30800</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5uxzw0c58cl668465</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al3ap0fc216050</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1et2eke87277</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
</tr>
</tbody>
</table>

<p>558811 rows × 15 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename "Mmr" column to be more readable</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">"Mmr"</span>: <span class="st">"MMR"</span>})</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">MMR</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5xyktca69fg566472</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5xyktca69fg561319</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba3c1c51ek116351</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">yv1612tb4f1310987</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.1</td>
<td>14282.0</td>
<td>White</td>
<td>Black</td>
<td>Volvo Na Rep/world Omni</td>
<td>27500</td>
<td>27750</td>
<td>2015-01-29 04:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba6b2c57ed129731</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">knalw4d4xf6019304</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3c6td5et6cg112407</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>WA</td>
<td>5.0</td>
<td>54393.0</td>
<td>White</td>
<td>Black</td>
<td>I -5 Uhlmann Rv</td>
<td>30200</td>
<td>30800</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5uxzw0c58cl668465</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al3ap0fc216050</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1et2eke87277</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
</tr>
</tbody>
</table>

<p>558811 rows × 15 columns</p>
</div>
</div>
</div>
<p>In the following 2 code snippets, I tried to filter out the number of entries in the dataset such that to make the data more skewed toward the present, giving us the ability to make conclusions that are relevant to the modern day, but also to avoid issues of utilizing vehicle entries with a (subjectively insignificant) numerical quantity toward future visualizations and future Machine Learning model training.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop all entries to only include entries sold between 2005 - 2015</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (making the dataset easier to train Machine Learning models and visualize)</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(labels<span class="op">=</span>df[df[<span class="st">"Year"</span>] <span class="op">&lt;</span> <span class="dv">2005</span>].index, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">MMR</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5xyktca69fg566472</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5xyktca69fg561319</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba3c1c51ek116351</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">yv1612tb4f1310987</td>
<td>2015</td>
<td>Volvo</td>
<td>S60</td>
<td>T5</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.1</td>
<td>14282.0</td>
<td>White</td>
<td>Black</td>
<td>Volvo Na Rep/world Omni</td>
<td>27500</td>
<td>27750</td>
<td>2015-01-29 04:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba6b2c57ed129731</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">knalw4d4xf6019304</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3c6td5et6cg112407</td>
<td>2012</td>
<td>Ram</td>
<td>2500</td>
<td>Power Wagon</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>WA</td>
<td>5.0</td>
<td>54393.0</td>
<td>White</td>
<td>Black</td>
<td>I -5 Uhlmann Rv</td>
<td>30200</td>
<td>30800</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5uxzw0c58cl668465</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al3ap0fc216050</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1et2eke87277</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
</tr>
</tbody>
</table>

<p>497245 rows × 15 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove car entries that are not significant for reporting in data</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># analysis &amp; visualization and to put toward Machine Learning model training</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>make_counts <span class="op">=</span> df[<span class="st">"Make"</span>].value_counts()</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[<span class="op">~</span>df[<span class="st">"Make"</span>].isin(make_counts[make_counts <span class="op">&lt;</span> <span class="dv">10000</span>].index)]</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>body_counts <span class="op">=</span> df[<span class="st">"Body"</span>].value_counts()</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[<span class="op">~</span>df[<span class="st">"Body"</span>].isin(body_counts[body_counts <span class="op">&lt;</span> <span class="dv">5000</span>].index)]</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>color_counts <span class="op">=</span> df[<span class="st">"Color"</span>].value_counts()</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[<span class="op">~</span>df[<span class="st">"Color"</span>].isin(color_counts[color_counts <span class="op">&lt;</span> <span class="dv">5000</span>].index)]</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>interior_counts <span class="op">=</span> df[<span class="st">"Interior"</span>].value_counts()</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[<span class="op">~</span>df[<span class="st">"Interior"</span>].isin(interior_counts[interior_counts <span class="op">&lt;</span> <span class="dv">1000</span>].index)]</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>state_counts <span class="op">=</span> df[<span class="st">"State"</span>].value_counts()</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[<span class="op">~</span>df[<span class="st">"State"</span>].isin(state_counts[state_counts <span class="op">&lt;</span> <span class="dv">1000</span>].index)]</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">MMR</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5xyktca69fg566472</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5xyktca69fg561319</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba3c1c51ek116351</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">wba6b2c57ed129731</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1n4al3ap1fn326013</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>1.0</td>
<td>5554.0</td>
<td>Gray</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15350</td>
<td>10900</td>
<td>2014-12-30 12:00:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wbafr1c53bc744672</td>
<td>2011</td>
<td>BMW</td>
<td>5 series</td>
<td>528i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>FL</td>
<td>3.9</td>
<td>66403.0</td>
<td>White</td>
<td>Brown</td>
<td>Lauderdale Imports Ltd Bmw Pembrok Pines</td>
<td>20300</td>
<td>22800</td>
<td>2015-07-07 06:15:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">knalw4d4xf6019304</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5uxzw0c58cl668465</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al3ap0fc216050</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1et2eke87277</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
</tr>
</tbody>
</table>

<p>375113 rows × 15 columns</p>
</div>
</div>
</div>
<p>Here, I am trying to offer some visualizations of the cleaned dataset before we pass it over for Machine Learning training and prediction. In this blog post, I wanted to visualize the counts of all of the different types of entries within each descriptive column as a bar graph to show the spread in the graph: Year, Make, Body, Transmission (Type), State (Registered), Color (of Exterior Body), and Interior (Primary Color).</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar graphs for descriptive statistics of the cars, figuring out how</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># many fall into which group within each qualitative cateogry</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_bar_graphs(attribute: <span class="bu">str</span>):</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    sns.countplot(x<span class="op">=</span>attribute, data<span class="op">=</span>df)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f"</span><span class="sc">{</span>attribute<span class="sc">}</span><span class="ss"> Comparison Across All Auctioning Used-Cars in the Dataset (2005-2015)"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">"font.size"</span>] <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>categorical_columns <span class="op">=</span> [<span class="st">"Year"</span>, <span class="st">"Make"</span>, <span class="st">"Body"</span>, <span class="st">"Transmission"</span>, <span class="st">"State"</span>, <span class="st">"Color"</span>, <span class="st">"Interior"</span>]</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> categorical_columns:</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    create_bar_graphs(col)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-7.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="machine-learning---model-training-and-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning---model-training-and-evaluation">Machine Learning - Model Training and Evaluation</h2>
<p>Great, now we are onto the Machine Learning part of the blog post!</p>
<p>As seen while cleaning the dataset above, this dataset was more used for data science applications. However, as mentioned above, I found a way to convert this into a Machine-Learning related study. Through seeing the profit made by selling the car compared to its market-valued price, determining the return-of-investment (ROI) made on the vehicle introduces the concept of binary classification here. Thus, to account for the ROI calcuation in my dataframe, I created a new column (as shown below) by subtracting the <code>Selling Price</code> columns and the <code>MMR (Manheim Market Report)</code> columns.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert this into a binary classification problem by separating cars based on</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># if each car entry (row) made a profit or not</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># First we are calculating the price sold when compared to the average MMR </span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># (Manheim Market Report)</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"ROI"</span>] <span class="op">=</span> df[<span class="st">"Selling Price"</span>] <span class="op">-</span> df[<span class="st">"MMR"</span>]</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">MMR</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
<th data-quarto-table-cell-role="th">ROI</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5xyktca69fg566472</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
<td>1000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5xyktca69fg561319</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
<td>700</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba3c1c51ek116351</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
<td>-1900</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">wba6b2c57ed129731</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
<td>1000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1n4al3ap1fn326013</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>1.0</td>
<td>5554.0</td>
<td>Gray</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15350</td>
<td>10900</td>
<td>2014-12-30 12:00:00</td>
<td>-4450</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wbafr1c53bc744672</td>
<td>2011</td>
<td>BMW</td>
<td>5 series</td>
<td>528i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>FL</td>
<td>3.9</td>
<td>66403.0</td>
<td>White</td>
<td>Brown</td>
<td>Lauderdale Imports Ltd Bmw Pembrok Pines</td>
<td>20300</td>
<td>22800</td>
<td>2015-07-07 06:15:00</td>
<td>2500</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">knalw4d4xf6019304</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
<td>-2300</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5uxzw0c58cl668465</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
<td>4200</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al3ap0fc216050</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
<td>-4000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1et2eke87277</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
<td>-2900</td>
</tr>
</tbody>
</table>

<p>375113 rows × 16 columns</p>
</div>
</div>
</div>
<p>As I was curious about the range of the ROI calcuation data, I created a histogram to illustrate the ROI spread across all car models and years currently in my working dataset.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram plot illustrating the ROI across all of the cars</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">"ROI"</span>])</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"font.size"</span>] <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Histogram ROI Comparison (Against MMR) Across All Auctioning Used-Cars in the Dataset (2005-2015)"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="op">-</span><span class="dv">8000</span>, <span class="dv">6000</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="dv">10000</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Because many of the Machine Learning algoritm functions can only take in numerical, standardized input, I decided to standardized it using True/False (for now), indiciating whether a profit was made or not. Ultimately, it does not matter what the ROI price was for each car but rather if it made a profit (positive ROI) or loss (negative or 0 ROI) at the moment of the sale. Later, I will convert the True/False values to its binary equivalent, 0 and 1.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting to the binary classification, slowly reordering the ROI column to </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># binary 0 or 1</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Now: False (failure) and True (Success)</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"ROI"</span>] <span class="op">=</span> ((df[<span class="st">"Selling Price"</span>] <span class="op">-</span> df[<span class="st">"MMR"</span>]) <span class="op">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">MMR</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
<th data-quarto-table-cell-role="th">ROI</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5xyktca69fg566472</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>16639.0</td>
<td>White</td>
<td>Black</td>
<td>Kia Motors America, Inc</td>
<td>20500</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5xyktca69fg561319</td>
<td>2015</td>
<td>Kia</td>
<td>Sorento</td>
<td>LX</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>5.0</td>
<td>9393.0</td>
<td>White</td>
<td>Beige</td>
<td>Kia Motors America, Inc</td>
<td>20800</td>
<td>21500</td>
<td>2014-12-16 12:30:00</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wba3c1c51ek116351</td>
<td>2014</td>
<td>BMW</td>
<td>3 series</td>
<td>328i SULEV</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.5</td>
<td>1331.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>31900</td>
<td>30000</td>
<td>2015-01-15 04:30:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">wba6b2c57ed129731</td>
<td>2014</td>
<td>BMW</td>
<td>6 series gran coupe</td>
<td>650i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>4.3</td>
<td>2641.0</td>
<td>Gray</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>66000</td>
<td>67000</td>
<td>2014-12-18 12:30:00</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1n4al3ap1fn326013</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>CA</td>
<td>1.0</td>
<td>5554.0</td>
<td>Gray</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15350</td>
<td>10900</td>
<td>2014-12-30 12:00:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">wbafr1c53bc744672</td>
<td>2011</td>
<td>BMW</td>
<td>5 series</td>
<td>528i</td>
<td>Sedan</td>
<td>Automatic</td>
<td>FL</td>
<td>3.9</td>
<td>66403.0</td>
<td>White</td>
<td>Brown</td>
<td>Lauderdale Imports Ltd Bmw Pembrok Pines</td>
<td>20300</td>
<td>22800</td>
<td>2015-07-07 06:15:00</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">knalw4d4xf6019304</td>
<td>2015</td>
<td>Kia</td>
<td>K900</td>
<td>Luxury</td>
<td>Sedan</td>
<td>Manual</td>
<td>IN</td>
<td>4.5</td>
<td>18255.0</td>
<td>Silver</td>
<td>Black</td>
<td>Avis Corporation</td>
<td>35300</td>
<td>33000</td>
<td>2015-07-09 07:00:00</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5uxzw0c58cl668465</td>
<td>2012</td>
<td>BMW</td>
<td>X5</td>
<td>xDrive35d</td>
<td>Suv</td>
<td>Automatic</td>
<td>CA</td>
<td>4.8</td>
<td>50561.0</td>
<td>Black</td>
<td>Black</td>
<td>Financial Services Remarketing (Lease)</td>
<td>29800</td>
<td>34000</td>
<td>2015-07-08 09:30:00</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al3ap0fc216050</td>
<td>2015</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>GA</td>
<td>3.8</td>
<td>16658.0</td>
<td>White</td>
<td>Black</td>
<td>Enterprise Vehicle Exchange / Tra / Rental / T...</td>
<td>15100</td>
<td>11100</td>
<td>2015-07-09 06:45:00</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1et2eke87277</td>
<td>2014</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>CA</td>
<td>3.4</td>
<td>15008.0</td>
<td>Gray</td>
<td>Gray</td>
<td>Ford Motor Credit Company,llc Pd</td>
<td>29600</td>
<td>26700</td>
<td>2015-05-28 05:30:00</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>375113 rows × 16 columns</p>
</div>
</div>
</div>
<p>Once more, before I pass my dataset over to the Machine Learning algorithms, I would like to sort all of the working car entries in my dataframe by all of its important categorical features in a hierarchy for visual reasons using the <code>sort_values</code> function - <code>Sale Date</code>, <code>Condition</code>, <code>Year</code>, <code>Make</code>, <code>ROI</code>, and <code>Odometer</code> - so that I can have a better organized picture of the final dataframe I will be working with prior to imposing any Machine Learning onto this.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort values in the table in order by column to show a hierarchy of </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># importance between comparable attributes of Auctioning Used-Cars</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># from the 2005-2015 time period</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>df.sort_values(by<span class="op">=</span>[<span class="st">"Sale Date"</span>, <span class="st">"Condition"</span>, <span class="st">"Year"</span>, <span class="st">"Make"</span>, <span class="st">"ROI"</span>, <span class="st">"Odometer"</span>], ascending<span class="op">=</span>[<span class="va">False</span>, <span class="va">False</span>, <span class="va">False</span>, <span class="va">True</span>, <span class="va">False</span>, <span class="va">False</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Trim</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">State</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">Seller</th>
<th data-quarto-table-cell-role="th">MMR</th>
<th data-quarto-table-cell-role="th">Selling Price</th>
<th data-quarto-table-cell-role="th">Sale Date</th>
<th data-quarto-table-cell-role="th">ROI</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1gnfc13007r166874</td>
<td>2007</td>
<td>Chevrolet</td>
<td>Tahoe</td>
<td>LT</td>
<td>Suv</td>
<td>Automatic</td>
<td>FL</td>
<td>2.3</td>
<td>1.0</td>
<td>White</td>
<td>Black</td>
<td>Autonation Ford Sanford</td>
<td>10450</td>
<td>9100</td>
<td>2015-07-21 02:30:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3gcukrec4eg454516</td>
<td>2014</td>
<td>Chevrolet</td>
<td>Silverado 1500</td>
<td>LT</td>
<td>Crewcab</td>
<td>Manual</td>
<td>PA</td>
<td>4.9</td>
<td>26294.0</td>
<td>Red</td>
<td>Black</td>
<td>Enterprise Veh Exchange/rental</td>
<td>30700</td>
<td>29000</td>
<td>2015-07-14 06:30:00</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1ef0dfb68283</td>
<td>2013</td>
<td>Ford</td>
<td>F-150</td>
<td>XLT</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>MS</td>
<td>4.4</td>
<td>47046.0</td>
<td>White</td>
<td>Gray</td>
<td>The Hertz Corporation</td>
<td>24800</td>
<td>24600</td>
<td>2015-07-14 06:30:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1gc1kxcg1cf125803</td>
<td>2012</td>
<td>Chevrolet</td>
<td>Silverado 2500hd</td>
<td>LT</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>TX</td>
<td>4.4</td>
<td>89312.0</td>
<td>Red</td>
<td>Black</td>
<td>Donlen Corporation</td>
<td>22200</td>
<td>22800</td>
<td>2015-07-14 06:30:00</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1ef6dkf58506</td>
<td>2013</td>
<td>Ford</td>
<td>F-150</td>
<td>XL</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>TX</td>
<td>4.1</td>
<td>52992.0</td>
<td>White</td>
<td>Gray</td>
<td>Enterprise Fleet Management Exchange</td>
<td>24200</td>
<td>18100</td>
<td>2015-07-14 06:30:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">kmhfc46f26a137010</td>
<td>2006</td>
<td>Hyundai</td>
<td>Azera</td>
<td>SE</td>
<td>Sedan</td>
<td>Automatic</td>
<td>SC</td>
<td>2.7</td>
<td>130948.0</td>
<td>White</td>
<td>Beige</td>
<td>Automobile Acceptance Corp</td>
<td>4575</td>
<td>4100</td>
<td>2014-01-01 09:15:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1g1pg5sc0c7199389</td>
<td>2012</td>
<td>Chevrolet</td>
<td>Cruze</td>
<td>2LT</td>
<td>Sedan</td>
<td>Automatic</td>
<td>SC</td>
<td>2.5</td>
<td>50457.0</td>
<td>White</td>
<td>Black</td>
<td>The Hertz Corporation</td>
<td>9750</td>
<td>8900</td>
<td>2014-01-01 09:15:00</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3gnec12z96g177687</td>
<td>2006</td>
<td>Chevrolet</td>
<td>Avalanche</td>
<td>1500 LS</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>SC</td>
<td>2.1</td>
<td>99247.0</td>
<td>Black</td>
<td>Gray</td>
<td>Pra Receivables Management Llc</td>
<td>7500</td>
<td>6800</td>
<td>2014-01-01 09:15:00</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al2ap4cn471701</td>
<td>2012</td>
<td>Nissan</td>
<td>Altima</td>
<td>2.5 S</td>
<td>Sedan</td>
<td>Automatic</td>
<td>SC</td>
<td>1.9</td>
<td>84325.0</td>
<td>Blue</td>
<td>Black</td>
<td>South Carolina State Credit Union</td>
<td>8600</td>
<td>7300</td>
<td>2014-01-01 09:15:00</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2b3ka43r48h231886</td>
<td>2008</td>
<td>Dodge</td>
<td>Charger</td>
<td>Base</td>
<td>Sedan</td>
<td>Automatic</td>
<td>SC</td>
<td>1.9</td>
<td>154031.0</td>
<td>Silver</td>
<td>Black</td>
<td>South Carolina State Credit Union</td>
<td>3950</td>
<td>3800</td>
<td>2014-01-01 09:15:00</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>375113 rows × 16 columns</p>
</div>
</div>
</div>
<p>With all of the entries sorted into its final positions in the dataframe, I found no need for certain categorical columns to be considered in the Machine Learning algorithms: <code>Seller</code>, <code>MMR</code>, <code>Selling Price</code>, <code>Trim</code>, <code>State</code>, <code>Model</code>, and <code>Sale Date</code>. Thus, I dropped them from my working dataframe to consolidate the dataset to those columns that I found relevant for car entry evaluation.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop these purely categorical columns (not needed in Machine Learning algorithms</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># which require only numerical input)</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>df.drop([<span class="st">"Seller"</span>, <span class="st">"MMR"</span>, <span class="st">"Selling Price"</span>, </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Trim"</span>, <span class="st">"State"</span>, <span class="st">"Model"</span>, <span class="st">"Sale Date"</span>], axis<span class="op">=</span><span class="dv">1</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Color</th>
<th data-quarto-table-cell-role="th">Interior</th>
<th data-quarto-table-cell-role="th">ROI</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1gnfc13007r166874</td>
<td>2007</td>
<td>Chevrolet</td>
<td>Suv</td>
<td>Automatic</td>
<td>2.3</td>
<td>1.0</td>
<td>White</td>
<td>Black</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3gcukrec4eg454516</td>
<td>2014</td>
<td>Chevrolet</td>
<td>Crewcab</td>
<td>Manual</td>
<td>4.9</td>
<td>26294.0</td>
<td>Red</td>
<td>Black</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1ef0dfb68283</td>
<td>2013</td>
<td>Ford</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>4.4</td>
<td>47046.0</td>
<td>White</td>
<td>Gray</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1gc1kxcg1cf125803</td>
<td>2012</td>
<td>Chevrolet</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>4.4</td>
<td>89312.0</td>
<td>Red</td>
<td>Black</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1ef6dkf58506</td>
<td>2013</td>
<td>Ford</td>
<td>Supercrew</td>
<td>Automatic</td>
<td>4.1</td>
<td>52992.0</td>
<td>White</td>
<td>Gray</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">kmhfc46f26a137010</td>
<td>2006</td>
<td>Hyundai</td>
<td>Sedan</td>
<td>Automatic</td>
<td>2.7</td>
<td>130948.0</td>
<td>White</td>
<td>Beige</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1g1pg5sc0c7199389</td>
<td>2012</td>
<td>Chevrolet</td>
<td>Sedan</td>
<td>Automatic</td>
<td>2.5</td>
<td>50457.0</td>
<td>White</td>
<td>Black</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3gnec12z96g177687</td>
<td>2006</td>
<td>Chevrolet</td>
<td>Crewcab</td>
<td>Automatic</td>
<td>2.1</td>
<td>99247.0</td>
<td>Black</td>
<td>Gray</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al2ap4cn471701</td>
<td>2012</td>
<td>Nissan</td>
<td>Sedan</td>
<td>Automatic</td>
<td>1.9</td>
<td>84325.0</td>
<td>Blue</td>
<td>Black</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2b3ka43r48h231886</td>
<td>2008</td>
<td>Dodge</td>
<td>Sedan</td>
<td>Automatic</td>
<td>1.9</td>
<td>154031.0</td>
<td>Silver</td>
<td>Black</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>375113 rows × 9 columns</p>
</div>
</div>
</div>
<p>As described before, the Machine Learning algoritm functions can only take in numerical, standardized input, so I decided to standardized the all of the rest of the categorical columns used in the evaluation of these used-car entries - <code>ROI</code>, <code>Transmission</code>, <code>Exterior Color</code>, <code>Matching Colors for Car Exterior and Interior</code>, <code>Make</code>, and <code>Body</code> - to numerical inputs using standard index mapping assignment in Python.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all necessary columns to an associated numerical value so that</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># they may be accepted as quantiative input to train the Machine Learning model</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">"Color"</span>: <span class="st">"Exterior Color"</span>, <span class="st">"Interior"</span>: <span class="st">"Matching Colors for Car Exterior and Interior"</span>})</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Matching Colors for Car Exterior and Interior"</span>] <span class="op">=</span> (df[<span class="st">"Matching Colors for Car Exterior and Interior"</span>] <span class="op">==</span> df[<span class="st">"Exterior Color"</span>])</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"ROI"</span>] <span class="op">=</span> df[<span class="st">"ROI"</span>].<span class="bu">map</span>({<span class="va">True</span>: <span class="dv">1</span>, <span class="va">False</span>: <span class="dv">0</span>}).astype(<span class="bu">int</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Transmission"</span>] <span class="op">=</span> df[<span class="st">"Transmission"</span>].<span class="bu">map</span>({<span class="st">"Automatic"</span>: <span class="dv">0</span>, <span class="st">"Manual"</span>: <span class="dv">1</span>}).astype(<span class="bu">int</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Matching Colors for Car Exterior and Interior"</span>] <span class="op">=</span> df[<span class="st">"Matching Colors for Car Exterior and Interior"</span>].<span class="bu">map</span>({<span class="va">True</span>: <span class="dv">1</span>, <span class="va">False</span>: <span class="dv">0</span>}).astype(<span class="bu">int</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Exterior Color"</span>] <span class="op">=</span> df[<span class="st">"Exterior Color"</span>].<span class="bu">map</span>({<span class="st">"Black"</span>: <span class="dv">0</span>, <span class="st">"White"</span>: <span class="dv">1</span>, <span class="st">"Gray"</span>: <span class="dv">2</span>, <span class="st">"Silver"</span>: <span class="dv">3</span>, <span class="st">"Blue"</span>: <span class="dv">4</span>, <span class="st">"Red"</span>: <span class="dv">5</span>, <span class="st">"Gold"</span>: <span class="dv">6</span>, <span class="st">"Burgundy"</span>: <span class="dv">7</span>, <span class="st">"Beige"</span>: <span class="dv">8</span>, <span class="st">"Green"</span>: <span class="dv">9</span>, <span class="st">"(Unknown)"</span>: <span class="dv">10</span>}).astype(<span class="bu">int</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Make"</span>] <span class="op">=</span> df[<span class="st">"Make"</span>].<span class="bu">map</span>({<span class="st">"Ford"</span>: <span class="dv">0</span>, <span class="st">"Nissan"</span>: <span class="dv">1</span>, <span class="st">"Chevrolet"</span>: <span class="dv">2</span>, <span class="st">"Toyota"</span>: <span class="dv">3</span>, <span class="st">"Dodge"</span>: <span class="dv">4</span>, <span class="st">"Honda"</span>: <span class="dv">5</span>, <span class="st">"Hyundai"</span>: <span class="dv">6</span>, <span class="st">"BMW"</span>: <span class="dv">7</span>, <span class="st">"Kia"</span>: <span class="dv">8</span>, <span class="st">"Chrysler"</span>: <span class="dv">9</span>, <span class="st">"M-Benz"</span>: <span class="dv">10</span>, <span class="st">"Jeep"</span>: <span class="dv">11</span>, <span class="st">"Infiniti"</span>: <span class="dv">12</span>, </span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"VW"</span>: <span class="dv">13</span>, <span class="st">"Lexus"</span>: <span class="dv">14</span>}).astype(<span class="bu">int</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Body"</span>] <span class="op">=</span> df[<span class="st">"Body"</span>].<span class="bu">map</span>({<span class="st">"Sedan"</span>: <span class="dv">0</span>, <span class="st">"Suv"</span>: <span class="dv">1</span>, <span class="st">"Minivan"</span>: <span class="dv">2</span>, <span class="st">"Hatchback"</span>: <span class="dv">3</span>, <span class="st">"Coupe"</span>: <span class="dv">4</span>, <span class="st">"Crewcab"</span>: <span class="dv">5</span>, <span class="st">"Wagon"</span>: <span class="dv">6</span>, <span class="st">"Supercrew"</span>: <span class="dv">7</span>, <span class="st">"Convertible"</span>: <span class="dv">8</span>, <span class="st">"Gsedan"</span>: <span class="dv">9</span>}).astype(<span class="bu">int</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Make</th>
<th data-quarto-table-cell-role="th">Body</th>
<th data-quarto-table-cell-role="th">Transmission</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Odometer</th>
<th data-quarto-table-cell-role="th">Exterior Color</th>
<th data-quarto-table-cell-role="th">Matching Colors for Car Exterior and Interior</th>
<th data-quarto-table-cell-role="th">ROI</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Vin</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1gnfc13007r166874</td>
<td>2007</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>2.3</td>
<td>1.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3gcukrec4eg454516</td>
<td>2014</td>
<td>2</td>
<td>5</td>
<td>1</td>
<td>4.9</td>
<td>26294.0</td>
<td>5</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1ef0dfb68283</td>
<td>2013</td>
<td>0</td>
<td>7</td>
<td>0</td>
<td>4.4</td>
<td>47046.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1gc1kxcg1cf125803</td>
<td>2012</td>
<td>2</td>
<td>5</td>
<td>0</td>
<td>4.4</td>
<td>89312.0</td>
<td>5</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1ftfw1ef6dkf58506</td>
<td>2013</td>
<td>0</td>
<td>7</td>
<td>0</td>
<td>4.1</td>
<td>52992.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">kmhfc46f26a137010</td>
<td>2006</td>
<td>6</td>
<td>0</td>
<td>0</td>
<td>2.7</td>
<td>130948.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1g1pg5sc0c7199389</td>
<td>2012</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>2.5</td>
<td>50457.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3gnec12z96g177687</td>
<td>2006</td>
<td>2</td>
<td>5</td>
<td>0</td>
<td>2.1</td>
<td>99247.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1n4al2ap4cn471701</td>
<td>2012</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1.9</td>
<td>84325.0</td>
<td>4</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2b3ka43r48h231886</td>
<td>2008</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>1.9</td>
<td>154031.0</td>
<td>3</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>375113 rows × 9 columns</p>
</div>
</div>
</div>
<p>As all of the data in the working dataframe are now numerical, I wanted to preliminary-wise see the quantifiable correlation between the <code>ROI</code> columns and the rest in the dataset. Thus, using the <code>corr</code> function for dataframes with the <code>ROI</code> column, I created a heatmap and bar-graph visualizing the constrast between each car entries’ attribute columns and its ROI value.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation heatmap to quantify relationships between auctioning used-car</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># attributes</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>sns.heatmap(df.corr(), annot<span class="op">=</span><span class="va">True</span>, linewidths<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Correlation Heatmap Between All Auctioning Used-Cars Quantiative Factors (2005-2015)"</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation bar graph between ROI and all other auctioning used-car</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># attributes</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>target_corr <span class="op">=</span> df.corr()[<span class="st">"ROI"</span>].<span class="bu">abs</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>target_corr.index[<span class="dv">1</span>:], y<span class="op">=</span>target_corr.values[<span class="dv">1</span>:])</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Auctioned Car Features"</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Correlation with ROI"</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Correlation between ROI and Other Auctioned Car Features When Comparing Across All Auctioning Used-Cars in the Dataset (2005-2015)"</span>)</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-25-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-25-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Since the dataframe is now properly cleaned, sorted, and integer-mapped by this point, I had split the respective dataframe into the train and test datasets for the Machine Learning model with 80% going to the training dataset and the last 20% going to the test dataset. Fortunately, because order of the data sequentially does not matter here, I was able to utilize the <code>train_test_split</code> function for shuffling and randomization, making the future-generated Machine Learning model more unpredictable but also more objective in its returned model results.</p>
<p>Note that here I also used a <code>Pipeline</code> object from the <code>scikit-learn</code> package as well as the <code>MinMaxScaler</code> and the <code>StandardScaler</code> classes. On on hand, the <code>MinMaxScaler</code> class is useful for scaling columns to a specific range, usually between [0, 1], to maintain consistency. On the other hand, the <code>StandardScaler</code> class is useful for apply Z-score normaization/transformation on the data to avoid sensivite-prone Machine Learning algorithms which require appropriate scaling of the features within its trained dataset. As I learned from online, this <code>Pipeline</code> object is necesary to ensure appropriate preprocessing just before the dataset is passed to the Machine Learning model for training and later evaluation.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuring the Machine Learning Tensorflow Model by placing all other columns into the x</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># axis and ROI column into the y-axis</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop([<span class="st">"ROI"</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"ROI"</span>]</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"X Shape:"</span>, X.shape)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Y Shape:"</span>, y.shape)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline([</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"min_max_scaler"</span>, MinMaxScaler()),</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"std_scaler"</span>, StandardScaler())</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>X_train_copy <span class="op">=</span> X_train.copy()</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> pipeline.fit_transform(X_train)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> pipeline.transform(X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>X Shape: (375113, 8)
Y Shape: (375113,)</code></pre>
</div>
</div>
<p>Whenever the Machine Learning model is fitted, it would be a good time to evaluate the effectiveness of my model. Thus, I will calculate metrics (as shown below) such as <code>Precision Score</code>, <code>ROC-AUC (Receiver Operating Characteristic (Curve) - Area Under the Curve) Score</code>, <code>Precision Score</code>, <code>F1 Score</code>, <code>Recall Score</code>, and the <code>Confusion Matrix</code>. Thus, in the following code snippet, I have written a function called <code>print_score</code> to print out these statistics as well as a corresponding visualization of the confusion matrix. This function will be invoked after each type of classification model has been discussed to evaluate each one’s effectiveness objectively.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> print_score(model, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> train <span class="op">==</span> <span class="va">True</span>:</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>        y_pred <span class="op">=</span> model.predict(X_train)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>        clf_report <span class="op">=</span> pd.DataFrame(classification_report(y_true<span class="op">=</span>y_train, y_pred<span class="op">=</span>y_pred, output_dict<span class="op">=</span><span class="va">True</span>, zero_division<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Compute and output statistics for Precision, Accuracy, and ROC AUC Scores as well as the Classifcation Report</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Train Result:</span><span class="ch">\n</span><span class="st">================================================"</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Accuracy Score: </span><span class="sc">{</span>accuracy_score(y_train, y_pred) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"ROC AUC Score: </span><span class="sc">{</span>roc_auc_score(y_train, y_train_prob) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"CLASSIFICATION REPORT:</span><span class="ch">\n</span><span class="sc">{</span>clf_report<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Calculate and output Precision, Recall, F1-Score, and Confusion Matrix</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>        precision, recall, f1_score <span class="op">=</span> (<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>        precision, recall, f1_score, _ <span class="op">=</span> precision_recall_fscore_support(y_true<span class="op">=</span>y_train, y_pred<span class="op">=</span>y_pred, average<span class="op">=</span><span class="st">'binary'</span>)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>        model_performance_metrics: [<span class="bu">str</span>] <span class="op">=</span> [<span class="st">"Precision"</span>, <span class="st">"Recall"</span>, <span class="st">"F1_Score"</span>]</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>        model_performance_metrics_values: [<span class="bu">float</span>] <span class="op">=</span> [precision, recall, f1_score]</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Precision Score: </span><span class="sc">{</span>precision <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Recall Score: </span><span class="sc">{</span>recall <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"F1 Score: </span><span class="sc">{</span>f1_score <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Confusion Matrix:</span><span class="ch">\n</span><span class="sc">{</span>confusion_matrix(y_train, y_pred)<span class="sc">}</span><span class="ss">"</span>) </span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>        plt.bar(model_performance_metrics, model_performance_metrics_values, color<span class="op">=</span>[<span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"orange"</span>])</span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(<span class="st">"Metrics"</span>)</span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">"Score"</span>)</span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="st">"Recommendation Model Evaluation Metrics -- Training Data"</span>)</span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>        plt.show()</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>        sns.heatmap(confusion_matrix(y_train, y_pred), annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">'d'</span>, cmap<span class="op">=</span><span class="st">'Blues'</span>)</span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(<span class="st">"Predicted Label"</span>)</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">"True Label"</span>)</span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="st">"Confusion Matrix for Training Data"</span>)</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a>        plt.show()</span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> train <span class="op">==</span> <span class="va">False</span>:</span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a>        y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a>        clf_report <span class="op">=</span> pd.DataFrame(classification_report(y_true<span class="op">=</span>y_test, y_pred<span class="op">=</span>y_pred, output_dict<span class="op">=</span><span class="va">True</span>, zero_division<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Compute and output statistics for Precision, Accuracy, and ROC AUC Scores as well as the Classifcation Report</span></span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Test Result:</span><span class="ch">\n</span><span class="st">================================================"</span>)        </span>
<span id="cb37-48"><a href="#cb37-48" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Accuracy Score: </span><span class="sc">{</span>accuracy_score(y_test, y_pred) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-49"><a href="#cb37-49" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"ROC AUC Score: </span><span class="sc">{</span>roc_auc_score(y_test, y_test_prob) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"CLASSIFICATION REPORT:</span><span class="ch">\n</span><span class="sc">{</span>clf_report<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Calculate and output Precision, Recall, F1-Score, and Confusion Matrix</span></span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a>        precision, recall, f1_score <span class="op">=</span> (<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a>        precision, recall, f1_score, _ <span class="op">=</span> precision_recall_fscore_support(y_true<span class="op">=</span>y_test, y_pred<span class="op">=</span>y_pred, average<span class="op">=</span><span class="st">'binary'</span>)</span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a>        model_performance_metrics: [<span class="bu">str</span>] <span class="op">=</span> [<span class="st">"Precision"</span>, <span class="st">"Recall"</span>, <span class="st">"F1_Score"</span>]</span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a>        model_performance_metrics_values: [<span class="bu">float</span>] <span class="op">=</span> [precision, recall, f1_score]</span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Precision Score: </span><span class="sc">{</span>precision <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Recall Score: </span><span class="sc">{</span>recall <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"F1 Score: </span><span class="sc">{</span>f1_score <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb37-65"><a href="#cb37-65" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"_______________________________________________"</span>)</span>
<span id="cb37-66"><a href="#cb37-66" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Confusion Matrix:</span><span class="ch">\n</span><span class="sc">{</span>confusion_matrix(y_test, y_pred)<span class="sc">}</span><span class="ss">"</span>)  </span>
<span id="cb37-67"><a href="#cb37-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-68"><a href="#cb37-68" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb37-69"><a href="#cb37-69" aria-hidden="true" tabindex="-1"></a>        plt.bar(model_performance_metrics, model_performance_metrics_values, color<span class="op">=</span>[<span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"orange"</span>])</span>
<span id="cb37-70"><a href="#cb37-70" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(<span class="st">"Metrics"</span>)</span>
<span id="cb37-71"><a href="#cb37-71" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">"Score"</span>)</span>
<span id="cb37-72"><a href="#cb37-72" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="st">"Recommendation Model Evaluation Metrics -- Testing Data"</span>)</span>
<span id="cb37-73"><a href="#cb37-73" aria-hidden="true" tabindex="-1"></a>        plt.show() </span>
<span id="cb37-74"><a href="#cb37-74" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb37-75"><a href="#cb37-75" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb37-76"><a href="#cb37-76" aria-hidden="true" tabindex="-1"></a>        sns.heatmap(confusion_matrix(y_test, y_pred), annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">'d'</span>, cmap<span class="op">=</span><span class="st">'Blues'</span>)</span>
<span id="cb37-77"><a href="#cb37-77" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(<span class="st">"Predicted Label"</span>)</span>
<span id="cb37-78"><a href="#cb37-78" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">"True Label"</span>)</span>
<span id="cb37-79"><a href="#cb37-79" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="st">"Confusion Matrix for Testing Data"</span>)</span>
<span id="cb37-80"><a href="#cb37-80" aria-hidden="true" tabindex="-1"></a>        plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we are finally at the Machine Learning classification portion. To reinforce my understanding of the different methodologies covered at the beginning of this course with regards to different ways of doing Machine-Learing classification, I am going to constrast all four of the main classification methods covered in this course: <code>LogisticRegression</code>, <code>KNeighborsClassifier</code>, <code>RandomForestClassifier</code>, and the <code>DecisionTreeClassifier</code>, comparing all of them against all of the following metrics evaluated in the <code>print_score</code> function to see which method is the most representative and encompassing of the most-accurately depicting my working dataset of Auctioned Used-Cars.</p>
<p>First, I analyzed the <code>LogisticRegression</code> Classification algorithm by fitting, estimating the probability of the sample for each class in the model using the <code>predict_proba</code> function, and printing out the appropriate metrics and visualization of the confusion matrix using the <code>print_score</code> helper function created earlier in the code snippets above.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilize the X_train and X_test Datasets to apply it towards LogisticRegression</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>log_reg <span class="op">=</span> LogisticRegression(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>log_reg.fit(X_train, y_train)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>y_train_prob <span class="op">=</span> log_reg.predict_proba(X_train)[:, <span class="dv">1</span>]</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>y_test_prob <span class="op">=</span> log_reg.predict_proba(X_test)[:, <span class="dv">1</span>]</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>print_score(log_reg, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>print_score(log_reg, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train Result:
================================================
Accuracy Score: 64.88%
_______________________________________________
ROC AUC Score: 70.70%
_______________________________________________
CLASSIFICATION REPORT:
                       0              1  accuracy      macro avg  \
precision       0.669965       0.624459  0.648752       0.647212   
recall          0.671381       0.622954  0.648752       0.647168   
f1-score        0.670672       0.623706  0.648752       0.647189   
support    159863.000000  140227.000000  0.648752  300090.000000   

            weighted avg  
precision       0.648701  
recall          0.648752  
f1-score        0.648726  
support    300090.000000  
_______________________________________________
Precision Score: 62.45%
_______________________________________________
Recall Score: 62.30%
_______________________________________________
F1 Score: 62.37%
_______________________________________________
Confusion Matrix:
[[107329  52534]
 [ 52872  87355]]
Test Result:
================================================
Accuracy Score: 64.44%
_______________________________________________
ROC AUC Score: 70.35%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.666450      0.619177  0.644376      0.642813      0.644377
recall         0.666417      0.619212  0.644376      0.642814      0.644376
f1-score       0.666433      0.619194  0.644376      0.642814      0.644376
support    39993.000000  35030.000000  0.644376  75023.000000  75023.000000
_______________________________________________
Precision Score: 61.92%
_______________________________________________
Recall Score: 61.92%
_______________________________________________
F1 Score: 61.92%
_______________________________________________
Confusion Matrix:
[[26652 13341]
 [13339 21691]]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-28-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-28-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-28-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-28-output-5.png" class="img-fluid"></p>
</div>
</div>
<p>Second, I analyzed the <code>KNeighborsClassifier</code> Classification algorithm by fitting, estimating the probability of the sample for each class in the model using the <code>predict_proba</code> function, and printing out the appropriate metrics and visualization of the confusion matrix using the <code>print_score</code> helper function created earlier in the code snippets above.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilize the X_train and X_test Datasets to apply it towards KNeighborsClassifier</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>knn_classifier <span class="op">=</span> KNeighborsClassifier()</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>knn_classifier.fit(X_train, y_train)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>y_train_prob <span class="op">=</span> knn_classifier.predict_proba(X_train)[:, <span class="dv">1</span>]</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>y_test_prob <span class="op">=</span> knn_classifier.predict_proba(X_test)[:, <span class="dv">1</span>]</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>print_score(knn_classifier, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>print_score(knn_classifier, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train Result:
================================================
Accuracy Score: 74.77%
_______________________________________________
ROC AUC Score: 82.71%
_______________________________________________
CLASSIFICATION REPORT:
                       0              1  accuracy      macro avg  \
precision       0.761243       0.731942  0.747666       0.746592   
recall          0.766838       0.725809  0.747666       0.746323   
f1-score        0.764030       0.728863  0.747666       0.746446   
support    159863.000000  140227.000000  0.747666  300090.000000   

            weighted avg  
precision       0.747551  
recall          0.747666  
f1-score        0.747597  
support    300090.000000  
_______________________________________________
Precision Score: 73.19%
_______________________________________________
Recall Score: 72.58%
_______________________________________________
F1 Score: 72.89%
_______________________________________________
Confusion Matrix:
[[122589  37274]
 [ 38449 101778]]
Test Result:
================================================
Accuracy Score: 61.93%
_______________________________________________
ROC AUC Score: 65.97%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.642210      0.592868  0.619303      0.617539      0.619171
recall         0.645438      0.589466  0.619303      0.617452      0.619303
f1-score       0.643820      0.591162  0.619303      0.617491      0.619233
support    39993.000000  35030.000000  0.619303  75023.000000  75023.000000
_______________________________________________
Precision Score: 59.29%
_______________________________________________
Recall Score: 58.95%
_______________________________________________
F1 Score: 59.12%
_______________________________________________
Confusion Matrix:
[[25813 14180]
 [14381 20649]]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-29-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-29-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-29-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-29-output-5.png" class="img-fluid"></p>
</div>
</div>
<p>Third, I analyzed the <code>RandomForestClassifier</code> Classification algorithm by fitting, estimating the probability of the sample for each class in the model using the <code>predict_proba</code> function, and printing out the appropriate metrics and visualization of the confusion matrix using the <code>print_score</code> helper function created earlier in the code snippets above.</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilize the X_train and X_test Datasets to apply it towards RandomForestClassifier</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>rf_classifier <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span> <span class="dv">100</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>rf_classifier.fit(X_train, y_train)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>y_train_prob <span class="op">=</span> rf_classifier.predict_proba(X_train)[:, <span class="dv">1</span>]</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>y_test_prob <span class="op">=</span> rf_classifier.predict_proba(X_test)[:, <span class="dv">1</span>]</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>print_score(rf_classifier, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>print_score(rf_classifier, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train Result:
================================================
Accuracy Score: 99.99%
_______________________________________________
ROC AUC Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                       0              1  accuracy      macro avg  weighted avg
precision       0.999900       0.999836   0.99987       0.999868       0.99987
recall          0.999856       0.999886   0.99987       0.999871       0.99987
f1-score        0.999878       0.999861   0.99987       0.999869       0.99987
support    159863.000000  140227.000000   0.99987  300090.000000  300090.00000
_______________________________________________
Precision Score: 99.98%
_______________________________________________
Recall Score: 99.99%
_______________________________________________
F1 Score: 99.99%
_______________________________________________
Confusion Matrix:
[[159840     23]
 [    16 140211]]
Test Result:
================================================
Accuracy Score: 62.19%
_______________________________________________
ROC AUC Score: 67.23%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.642706      0.597257  0.621943      0.619982      0.621485
recall         0.654840      0.584385  0.621943      0.619612      0.621943
f1-score       0.648716      0.590751  0.621943      0.619734      0.621651
support    39993.000000  35030.000000  0.621943  75023.000000  75023.000000
_______________________________________________
Precision Score: 59.73%
_______________________________________________
Recall Score: 58.44%
_______________________________________________
F1 Score: 59.08%
_______________________________________________
Confusion Matrix:
[[26189 13804]
 [14559 20471]]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-30-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-30-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-30-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-30-output-5.png" class="img-fluid"></p>
</div>
</div>
<p>For the Random-Forest Classification, I wanted to create an additional visualization seeing what categorical columns were most correlated in predicting the <code>ROI</code> column. Thus, I made a bar plot to illustrate and map each categorical relationship’s correlation as shown below.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creates a visualization for the Random-Forest Classifier data</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>rf_visualization <span class="op">=</span> pd.Series(rf_classifier.feature_importances_, index<span class="op">=</span>df.columns.tolist()[<span class="dv">1</span>:]).sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>rf_visualization, y<span class="op">=</span>rf_visualization.index)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Feature Importance Score"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>plt.yticks(rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Features"</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Visualizing Important Features of Auctioning Used-Car Data After Random Forest Classification"</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-31-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Lastly, I analyzed the <code>DecisionTreeClassifier</code> Classification algorithm by fitting, estimating the probability of the sample for each class in the model using the <code>predict_proba</code> function, and printing out the appropriate metrics and visualization of the confusion matrix using the <code>print_score</code> helper function created earlier in the code snippets above.</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilize the X_train and X_test Datasets to apply it towards DecisionTreeClassifier</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>dt_classifier <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>dt_classifier.fit(X_train, y_train)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>y_train_prob <span class="op">=</span> dt_classifier.predict_proba(X_train)[:, <span class="dv">1</span>]</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>y_test_prob <span class="op">=</span> dt_classifier.predict_proba(X_test)[:, <span class="dv">1</span>]</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>print_score(dt_classifier, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>print_score(dt_classifier, X_train, y_train, X_test, y_test, y_train_prob, y_test_prob, train<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train Result:
================================================
Accuracy Score: 64.07%
_______________________________________________
ROC AUC Score: 68.89%
_______________________________________________
CLASSIFICATION REPORT:
                       0              1  accuracy      macro avg  \
precision       0.652885       0.624744  0.640704       0.638814   
recall          0.695101       0.578690  0.640704       0.636896   
f1-score        0.673332       0.600836  0.640704       0.637084   
support    159863.000000  140227.000000  0.640704  300090.000000   

            weighted avg  
precision       0.639735  
recall          0.640704  
f1-score        0.639456  
support    300090.000000  
_______________________________________________
Precision Score: 62.47%
_______________________________________________
Recall Score: 57.87%
_______________________________________________
F1 Score: 60.08%
_______________________________________________
Confusion Matrix:
[[111121  48742]
 [ 59079  81148]]
Test Result:
================================================
Accuracy Score: 63.80%
_______________________________________________
ROC AUC Score: 68.63%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.651094      0.620869  0.637978      0.635981      0.636981
recall         0.691371      0.577020  0.637978      0.634195      0.637978
f1-score       0.670628      0.598142  0.637978      0.634385      0.636783
support    39993.000000  35030.000000  0.637978  75023.000000  75023.000000
_______________________________________________
Precision Score: 62.09%
_______________________________________________
Recall Score: 57.70%
_______________________________________________
F1 Score: 59.81%
_______________________________________________
Confusion Matrix:
[[27650 12343]
 [14817 20213]]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-32-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-32-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-32-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-32-output-5.png" class="img-fluid"></p>
</div>
</div>
<p>For the Random-Forest Classification, I wanted to create an additional visualization seeing what categorical columns were most correlated in predicting the <code>ROI</code> column. Thus, I made a bar plot to illustrate and map each categorical relationship’s correlation as shown below.</p>
<p>Similar to the Random-Forest Classification, I wanted to create an additional visualization to illustrate a portion of the Decision-Tree using the <code>plot_tree</code> function as shown below.</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creates a visualization for the Decision-Tree Classifier data</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">18</span>))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>sk.tree.plot_tree(dt_classifier, feature_names<span class="op">=</span>df.columns.tolist()[<span class="dv">1</span>:], filled<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                  class_names<span class="op">=</span>[<span class="st">"Negative ROI - Loss Money"</span>, <span class="st">"Positive ROI - Gain Money / Profited"</span>])</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Visualizing Decision Tree Classification"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-33-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<ul>
<li><p>Based on the four methods of classification invoked here in this blog post, the best classification predictor for this problem out of all of the methods is the <code>LogisticRegression</code> Classifier with the highest accuracy score of 64.44% as well as the highest average and consistency of all of the classifier algorithms used here with across the board scoring 61.92%.</p></li>
<li><p>After reviewing the heatmap called <code>Correlation Heatmap Between All Aunctioning Used-Cars Quantitative Fcctors (2005-2015)</code> and the bar graph called <code>Correlation between ROI and Other Auctioned Car Features When Comparing Across All Auctioning Used-Cars in the Dataset (2005-2015)</code> in the <code>Machine Learning - Model Training and Evaluation</code> section of this blog post, I was surprised to see that the <code>Condition</code> qualitative column most correlated with the <code>ROI</code> computed column (through the subtraction of the <code>Selling Price</code> and the <code>MMR</code> (Manheim Market Report) columns) with about approximately <code>30%</code> correlation, higher than the 2nd-most correlated column - <code>Transmission</code> - by far at approximately <code>2.5%</code> correlation. In my opinion, I feel that this could be justified due to the fact that most younger-car buyers prefer a nice, asthetic interior and exterior as a primary selling-point considering to buy a used-car. Most people would take the general assumption that if the used-car to consider buying does not look at initial inspection, most prospective car-buyers would not invest any time further in looking into the performance specifics of the vehicle. This specific pattern could follow when investigating into the <code>Machine Learning</code> section that the <code>RandomForestClassifier</code> that the <code>Exterior Color</code> played a significant factor in this classification algorithm. However, this inference could be ultimately inconclusive due its described randomness.</p></li>
<li><p>With careful experimentation in both the <code>Data Preprocessing - Cleaning and Analytics</code> and <code>Machine Learning - Model Training and Evaluation</code> sections of this blog post, it is of my opinion that the best factor that impacts <code>ROI</code> (and indirectly the classification of Used-Cars by human users) would be the <code>Condition</code> of the vehicle in-question at the time of sale.</p></li>
<li><p>Ultimately, I learned a great deal from the blog post experience as I now better understand how to properly utilize different types of simple/basic Machine Learning classification through applying it to a practical, every-day dilemma in our society.</p></li>
</ul>
</section>
<section id="reference-sources-and-citations-ieee-format" class="level2">
<h2 class="anchored" data-anchor-id="reference-sources-and-citations-ieee-format">Reference Sources and Citations (IEEE Format)</h2>
<p>To complete this blog post, I used the following online sources as references for developing this:</p>
<p>[1] Car Auctions Dataset (Only Used Dataset Not Kaggle Notebook):</p>
<p>G.S. Deepak Kumar, “Car Auctions - What influences the selling price?”, 2021. [Online]. Available: https://www.kaggle.com/code/gsdeepakkumar/car-auctions-what-influences-the-selling-price/input?select=car_prices.csv. [Accessed: 07-Sep.-2023].</p>
<p>[2] Tutorial on Calculating Basic Machine Learning Model Evaluation Statistics:</p>
<p>A. Essam, “Titanic Supervised Learning Classification”, Jul.-2023. [Online]. Available: https://www.kaggle.com/code/aliessamali/titanic-supervised-learning-classification. [Accessed: 08-Sep.-2023].</p>
<p>[3] Tutorial on Random Forest Classifiers:</p>
<p>P. Banerjee, “Random Forest Classifer Tutorial”, 2019. [Online.] Available: https://www.kaggle.com/code/prashant111/random-forest-classifier-tutorial. [Accessed: 07-Sep.-2023].</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>