name: GitHub Pages

on:
  push:
    branches:
      - main
      - angular

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        shell: bash
        working-directory: ./cs-5805-final-project-blog-posts/
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm install
    
    - name: Build GitHub Pages Angular Site
      run: npm run build -- --base-href https://${{github.actor}}.github.io/${{github.event.repository.name}}/

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        publish_dir: ./dist/${{github.event.repository.name}}/
        enable_jekyll: true
